import { useEffect, useState } from "react";
import { Link, useLocation, useParams } from "react-router-dom";
import api from "../api/client.js";

export default function OrderConfirmationPage() {
  const { id } = useParams();
  const location = useLocation();
  const [order, setOrder] = useState(location.state || null);
  const [loading, setLoading] = useState(!location.state);
  const [error, setError] = useState("");

  useEffect(() => {
    if (order) {
      const resolvedId = order.orderId || order._id || id;
      if (resolvedId) {
        window.localStorage.setItem("latestOrderId", String(resolvedId));
      }
      return;
    }
    async function fetchOrder() {
      try {
        const res = await api.get(`/orders/${id}`);
        setOrder(res.data);
        const resolvedId = res.data.orderId || res.data._id || id;
        if (resolvedId) {
          window.localStorage.setItem("latestOrderId", String(resolvedId));
        }
      } catch (err) {
        console.error(err);
        setError("Unable to fetch order details. Try placing a new order.");
      } finally {
        setLoading(false);
      }
    }
    fetchOrder();
  }, [id, order]);

  const impact = order?.impact_data;

  return (
    <section className="space-y-6">
      <header className="flex items-end justify-between gap-3">
        <div>
          <p className="pill-badge mb-2">Module 3 · Impact Reporting</p>
          <h1 className="text-2xl font-semibold tracking-tight text-slate-50">
            Order placed,{" "}
            <span className="text-emerald-300">impact calculated in real time.</span>
          </h1>
          <p className="mt-2 text-sm text-slate-400">
            This screen is driven by backend business logic and AI. Numbers are
            calculated deterministically; the narrative is generated by the model.
          </p>
        </div>
      </header>

      <div className="glass-panel p-4">
        {loading ? (
          <p className="text-sm text-slate-400">Loading order details…</p>
        ) : error ? (
          <p className="text-sm text-red-400">{error}</p>
        ) : (
          <>
            <div className="flex flex-col gap-3 border-b border-slate-800/80 pb-3 md:flex-row md:items-center md:justify-between">
              <div>
                <div className="text-xs text-slate-400">Order ID</div>
                <div className="text-sm font-mono text-slate-100">
                  {order.orderId || order._id}
                </div>
              </div>
              <div className="text-right">
                <div className="text-xs text-slate-400">Total amount</div>
                <div className="text-lg font-semibold text-emerald-300">
                  ₹{order.total_amount}
                </div>
              </div>
            </div>

            <div className="mt-4 grid gap-4 md:grid-cols-3">
              <div className="rounded-xl border border-emerald-500/40 bg-emerald-500/5 p-3">
                <div className="text-xs text-emerald-300">Plastic saved</div>
                <div className="mt-1 text-xl font-semibold text-emerald-200">
                  {impact?.plastic_saved_kg ?? "—"} kg
                </div>
                <p className="mt-1 text-[11px] text-emerald-200/80">
                  Based on per-product plastic offsets stored in the catalog.
                </p>
              </div>
              <div className="rounded-xl border border-sky-500/40 bg-sky-500/5 p-3">
                <div className="text-xs text-sky-300">Carbon avoided</div>
                <div className="mt-1 text-xl font-semibold text-sky-200">
                  {impact?.carbon_saved_kg ?? "—"} kg
                </div>
                <p className="mt-1 text-[11px] text-sky-200/80">
                  Aggregated from gram-level carbon savings per item.
                </p>
              </div>
              <div className="rounded-xl border border-amber-500/40 bg-amber-500/5 p-3">
                <div className="text-xs text-amber-300">Locally sourced items</div>
                <div className="mt-1 text-xl font-semibold text-amber-200">
                  {impact?.locally_sourced_count ?? 0}
                </div>
                <p className="mt-1 text-[11px] text-amber-200/80">
                  Products flagged as locally sourced in the product metadata.
                </p>
              </div>
            </div>

            <div className="mt-5 rounded-xl border border-slate-800/80 bg-slate-900/70 p-4">
              <div className="text-xs text-slate-400">AI-generated impact summary</div>
              <p className="mt-2 text-sm text-slate-100">
                {order.impact_statement ||
                  "Impact statement will appear here once AI integration is configured."}
              </p>
            </div>

            <div className="mt-4 flex items-center justify-between text-xs text-slate-400">
              <p>Need help with this order?</p>
              <Link
                to="/support"
                className="rounded-full border border-emerald-500/60 bg-emerald-500/10 px-3 py-1 text-[11px] font-medium text-emerald-200 hover:bg-emerald-500/20"
              >
                Open support chat about this order
              </Link>
            </div>
          </>
        )}
      </div>
    </section>
  );
}

